### PR TITLE
fix update created_at

### LINKED ISSUE #4: BulkInsertOnDuplicateKeyUpdate updates CreatedAt
When importing using the function BulkInsertOnDuplicateKeyUpdate, instead of keeping the createdAt value, this value gets updated

### PR DESCRIPTION
**Pull request by fnxpt**
Fixes #4

### CODE REVIEW

File: exec_func.go [hunk 1]
```diff
@@ -47,10 +47,12 @@ func InsertOnDuplicateKeyUpdateFunc(scope *gorm.Scope, columnNames, groups []str
 	var duplicateUpdates []string
 
 	for i := range columnNames {
-		duplicateUpdates = append(
-			duplicateUpdates,
-			fmt.Sprintf("%s = VALUES(%s)", columnNames[i], columnNames[i]),
-		)
+		if columnNames[i] != "`created_at`" {
```
Comment (bombsimon) [inline exec_func.go]: I would prefer if the [happy path was kept to the left](https://medium.com/@matryer/line-of-sight-in-code-186dd7cdea88) both since that's how the rest of the code is written but also because I think it's more readable. It would also be a good idea if there were more special cases in the future.

```go
if columnNames[i] == "`created_at`" {
    continue
}

// Move on and add columnn...
```

**Review by bombsimon — CHANGES_REQUESTED** [review]
Thank you for this, nice catch! I have one request about the coding style which I hope you find ok. I'll be glad to merge this PR when changed. 🚀

File: exec_func.go (hunk 1 above)
Comment (fnxpt) [reply exec_func.go]: Done

**Review by bombsimon — APPROVED** [review]
